/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0IsULnLly42
 */
import { Button } from "@/components/ui/button";

export function HydrationTracker() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center gap-4 p-4 md:gap-8 md:p-10">
      <div className="flex flex-col items-center gap-2">
        <h1 className="text-3xl font-bold">Hydration Tracker</h1>
        <p className="text-center text-gray-500 dark:text-gray-400">
          Tap the buttons to track your water intake. Stay hydrated!
        </p>
      </div>
      <div className="flex flex-col items-center gap-2">
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-2">
            <GlassWaterIcon className="h-6 w-6" />
            <span className="text-2xl font-semibold">3</span>
          </div>
          <span className="text-2xl">/8</span>
        </div>
        <div className="grid w-full gap-4 md:grid-cols-2">
          <Button className="w-full" variant="outline">
            + 1 Cup
          </Button>
          <Button className="w-full" variant="outline">
            - 1 Cup
          </Button>
        </div>
      </div>
      <div className="flex w-full max-w-sm flex-col gap-4">
        <div className="flex items-center justify-between">
          <div className="text-sm">Today</div>
          <div className="flex items-center gap-2">
            <GlassWaterIcon className="h-4 w-4" />
            <GlassWaterIcon className="h-4 w-4" />
            <GlassWaterIcon className="h-4 w-4" />
            <GlassWaterIcon className="h-4 w-4" />
            <GlassWaterIcon className="h-4 w-4" />
            <GlassWaterIcon className="h-4 w-4" />
            <GlassWaterIcon className="h-4 w-4" />
            <GlassWaterIcon className="h-4 w-4" />
          </div>
        </div>
        <div className="flex items-center justify-between">
          <div className="text-sm">Yesterday</div>
          <div className="flex items-center gap-2">
            <GlassWaterIcon className="h-4 w-4" />
            <GlassWaterIcon className="h-4 w-4" />
            <GlassWaterIcon className="h-4 w-4" />
            <GlassWaterIcon className="h-4 w-4" />
            <GlassWaterIcon className="h-4 w-4" />
            <GlassWaterIcon className="h-4 w-4" />
            <GlassWaterIcon className="h-4 w-4" />
            <GlassWaterIcon className="h-4 w-4" />
          </div>
        </div>
      </div>
    </div>
  );
}

function GlassWaterIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15.2 22H8.8a2 2 0 0 1-2-1.79L5 3h14l-1.81 17.21A2 2 0 0 1 15.2 22Z" />
      <path d="M6 12a5 5 0 0 1 6 0 5 5 0 0 0 6 0" />
    </svg>
  );
}
